on: push
name: build
jobs:
  go-pipeline:
    name: Go Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: go1.11 linter
        uses: ./go1.11/linter
        with:
          GOLINT: on
          MISSPELL: on
        env:
          PROJECT_PATH: test
      - name: go1.11 test
        uses: ./go1.11/test
        env:
          PROJECT_PATH: test
      - name: go1.12 linter
        uses: ./go1.12/linter
        with:
          GOLINT: on
          MISSPELL: on
        env:
          PROJECT_PATH: test
      - name: go1.12 test
        uses: ./go1.12/test
        env:
          PROJECT_PATH: test
      - name: go1.13 linter
        uses: ./go1.13/linter
        with:
          GOLINT: on
          MISSPELL: on
        env:
          PROJECT_PATH: test
      - name: go1.13 test
        uses: ./go1.13/test
        env:
          PROJECT_PATH: test
      - name: go1.14 linter
        uses: ./go1.14/linter
        with:
          GOLINT: on
          MISSPELL: on
        env:
          PROJECT_PATH: test
      - name: go1.14 test
        uses: ./go1.14/test
        env:
          PROJECT_PATH: test